### ISSUE TITLE
pb部署上线

### ISSUE THREAD

**Issue by Aliang-CN** [Mrzhang3389/text_class#7]
你好，可以讲讲pb部署上线的教程吗？

**Comment by zh3389** [comment]
安装好 docker后  pull tensorflow_serving镜像后执行以下 脚本
https://github.com/Mrzhang3389/text_class/blob/master/save_model/deploy.sh
然后使用客户端脚本就可以正常使用啦.
https://github.com/Mrzhang3389/text_class/blob/master/client.py
